#!/bin/bash

. /etc/sysconfig/qbiffd

if [ ! -f $QBIFF_SERVER_PWD ];then
    echo "qbiffd: no credentials found"
    exit 1
fi
stdbuf -i0 -o0 -e0 /usr/bin/qbiffd \
    -p ${QBIFF_PORT} \
    -f ${QBIFF_FOLDER} -s ${QBIFF_SERVER} \
&> /var/tmp/qbiffd.log < ${QBIFF_SERVER_PWD}
