#! /bin/sh
# Copyright (c) 2002,2003 SuSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Author: Marcus Schaefer
#
# /etc/init.d/qbiffd
#   and its symbolic link
# /usr/sbin/rcqbiffd
#

### BEGIN INIT INFO
# Provides:          qbiffd
# Required-Start:    $remote_fs $named $syslog
# Required-Stop:     $remote_fs $named $syslog
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       qbiffd mail notify daemon
# Short-Description: qbiffd mail notify daemon
### END INIT INFO

. /etc/rc.status
# First reset status of this service
rc_reset

# check for qbiff daemon
QBIFF_BIN="/usr/bin/qbiffd"
if [ ! -x $QBIFF_BIN ];then
	echo -n "qbiffd, $ATFTP_BIN is not installed."
	rc_status -s
	exit 5
fi

# set default environment
QBIFF_USER=${QBIFF_USER:="nobdoy"}
QBIFF_GROUP=${QBIFF_GROUP:="nogroup"}
QBIFF_PID_DIR="/var/run/qbiffd"

# set correct perm on pid_dir
set_perm(){
	[ ! -d "$QBIFF_PID_DIR" ] && /usr/bin/install -d "$QBIFF_PID_DIR";
	chown -R ${1}:${2} "$QBIFF_PID_DIR"
}

# read in sysconfig setup
[ -f /etc/sysconfig/qbiff ] && . /etc/sysconfig/qbiff

# go ahead
case "$1" in
	start)
		set_perm $QBIFF_USER $QBIFF_GROUP
		echo -n "Starting qbiff server"
		rm -f $QBIFF_PID_DIR/qbiff*.pid
		if [ ! -f $QBIFF_SERVER_PWD ];then
			echo "linux" > $QBIFF_SERVER_PWD
		fi
		if [ -x /usr/bin/dbus-launch ];then
			export $(dbus-launch)
		fi
		cat $QBIFF_SERVER_PWD | \
			qbiffd -u $QBIFF_USER -g $QBIFF_GROUP -d -p $QBIFF_PORT \
			-f $QBIFF_FOLDER -s $QBIFF_SERVER &>/dev/null &
		sleep 1
		kill -0 $! &>/dev/null || rc_failed
		rc_status -v
	;;
	stop)
		echo -n "Shutting down qbiff server"
		/sbin/killproc -p $QBIFF_PID_DIR/qbiff.$QBIFF_PORT.pid -TERM qbiffd
		rm -f $QBIFF_PID_DIR/qbiff.$QBIFF_PORT.pid
		rc_status -v
	;;
	restart)
		$0 stop
		$0 start
		rc_status
	;;
	reload)
		$0 stop
		$0 start
		rc_status
		;;
	status|check)
		echo -n "Checking for qbiff server"
		checkproc -p $QBIFF_PID_DIR/qbiff.$QBIFF_PORT.pid qbiff
		rc_status -v
	;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
esac
rc_exit
